# Generated by Django 3.2 on 2025-03-12 10:12

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20250311_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.models.Title.validate_year], verbose_name='Год издания'),
        ),
    ]
