# Generated by Django 3.2 on 2025-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20250311_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Краткое описание произведения'),
        ),
    ]
