# Generated by Django 3.2 on 2025-03-13 04:39

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.Title.validate_year], verbose_name='Год издания'),
        ),
    ]
